version: '2.10.2'
services:
  mongodb:
    image: mongo
    container_name: mongo_conainer
    restart: always
    ports:
      - 27017:27017


  api_rest:
    build: "./"
    container_name: desafio_capgemini
    restart: always
    volumes:
      - ./api_rest:/home/capgemini
    ports:
      - "8080:8080"
    depends_on:
      - mongodb